project_id = "ajwtlemiupyquwmhzxqi"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[functions.vehicle-lookup]
verify_jwt = false

[functions.create-quote]
verify_jwt = false

[functions.analyze-pds]
verify_jwt = false

[functions.suncorp-proxy]
verify_jwt = false
